server.port=8080
spring.application.name=agri-invest-backend

# Cloud MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://thrishajc16_db_user:74CEqWZ5egJ1qZe0@cluster0.jmuhui5.mongodb.net/agri_invest_ai?retryWrites=true&w=majority&appName=Cluster0

# Razorpay configuration
razorpay.key=${RAZORPAY_KEY:rzp_test_Scf5lduuYreoJg}
razorpay.secret=${RAZORPAY_SECRET:XnP4Ba2MsUCXqIqLrCs61wFD}

# Python AI Module Connection
ai.module.url=http://localhost:5001/recommend-crop